name: 'Set shared envs'
description: 'Set app name from repo and release version'
author: 'emvakar'
branding:
  icon: 'bell'
  color: blue

inputs:
  repository_git:
    description: 'Repository'
    required: true
  repository_owner:
    description: 'Repository owner'
    required: true
  commit_ref:
    description: 'Commit reference'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set App Name
      run: |
        str=${{ inputs.repository_git }}
        find="${{ inputs.repository_owner }}"
        replace=""
        result=${str//$find/$replace}
        echo "FOLDER_NAME=${result}" >> $GITHUB_ENV
      shell: bash
    - name: Setup Release version for app
      run: |
        env
        str="${{ inputs.commit_ref }}"
        find="release/"
        replace=""
        result=${str//$find/$replace}
        echo ${result}
        find="refs/heads/"
        replace=""
        result=${result//$find/$replace}
        echo ${result}
        echo "APP_VERSION=${result}" >> $GITHUB_ENV
      shell: bash
